useless scripts delete and errors fixes for roolButton
-unused dices delete
-changs in rollButton:
1.error fixed
2.code improved
-problem:
1.still has one error in rollButton:
error CS0246: The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)